### ISSUE TITLE
DEMOLISH documentation and implementation differ

### ISSUE THREAD

**Issue by tobyink** [dagolden/Class-Tiny#29]
Documentation says:

> Return values and errors are ignored.

But the implementation includes this:

```perl
die $e if $e;
```

Doesn't seem to be ignoring the error.

**Comment by xdg** [comment]
I suspect I was copying Moo.  Letting them all run and then throwing the first(?) error might make more sense.  At this point, though, I'm not really invested in a "right" answer.

**Comment by tobyink** [comment]
Could be related to https://github.com/perl/perl5/issues/14319
